version: '3'

services:
  registry:
    image: registry:2
    ports:
      - "192.168.129.137:5000:5000"
    environment:
      # Configure as pull-through cache
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
      # Basic authentication
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
      - registry-data:/var/lib/registry
      - ./auth:/auth
    restart: always
volumes:
  registry-data:

