# roles/vm_management/tasks/status.yml
---
- name: Show status of student VMs
  shell: lxc list "student*"
  register: status
  changed_when: false

- name: Display status
  debug:
    msg: "{{ status.stdout_lines }}"

- name: Display networking info
  command: lxc network list
  register: networks
  changed_when: false

- name: Show networks
  debug:
    msg: "{{ networks.stdout_lines }}"