# IPv4 setup
# Listen on specific port
agentaddress udp:${PORT}

# Community string setting
rocommunity ${COMMUNITY_STRING} 0.0.0.0/0

# System information
syslocation "CTF Training Environment"
syscontact "Admin <admin@ctf.local>"
sysname "${SYSTEM_NAME}"
