---
- name: Prepare the VM
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Generate random Vagrant password
      set_fact:
        random_vagrant_password: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters,digits') }}"

    - name: Change Vagrant password
      ansible.builtin.user:
        name: vagrant
        password: "{{ random_vagrant_password | password_hash('sha512', lookup('password', '/dev/null length=8 chars=ascii_letters,digits')) }}"
      become_user: root

    - name: Print random passwords to log
      ansible.builtin.debug:
        msg: "Random Vagrant Password: {{ random_vagrant_password }}"

    - name: Add Docker repository to Apt sources
      ansible.builtin.shell:
        cmd: rm -f /etc/netplan/*
      become: true

    - name: Create network configuration file if not exists
      copy:
        dest: /etc/netplan/01-netcfg.yaml
        content: |
          network:
            ethernets:
              eth0:
                dhcp4: true
                dhcp6: false
            version: 2
      become: true            

    - name: Apply the new network configuration
      command: netplan apply
      become: true

    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: yes      

    - name: Update the kernel
      ansible.builtin.apt:
        name:
          - linux-image-generic-hwe-22.04
        state: present
      become: true

    - name: Reboot the server
      ansible.builtin.reboot:
      become: true

    - name: Wait for server to become reachable
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        delay: 10
        timeout: 300

    - name: Install prerequisites for Docker
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - net-tools
        state: present
      become: true

    - name: Add Docker repository to Apt sources
      ansible.builtin.shell:
        cmd: |
            # Add Docker's official GPG key:
            sudo install -m 0755 -d /etc/apt/keyrings
            sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
            sudo chmod a+r /etc/apt/keyrings/docker.asc

            # Add the repository to Apt sources:
            echo \
              "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
              $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
              sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      become: true

    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: yes           

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-compose
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
      become: true

    - name: Add vagrant to the docker group
      ansible.builtin.user:
        name: vagrant
        groups: docker
        append: yes

    - name: Copy docker-compose to home directory
      ansible.builtin.copy:
        src: docker-compose_1.yml
        dest: /home/vagrant/docker-compose.yml
      become_user: vagrant

    - name: Set up environment 1
      include_role:
        name: setup_role
      vars:
        setup_number: 1

    - name: Clean up existing Docker containers and images
      shell: |
        docker-compose down --volumes --remove-orphans
        docker system prune -af
      ignore_errors: true      

    - name: Check if Docker Compose service is running
      shell: docker-compose ps -q
      register: compose_status
      ignore_errors: true

    - name: Restart Docker Compose service if running
      command: docker-compose -f /home/vagrant/docker-compose.yml restart
      when: compose_status.stdout | length > 0

    - name: Start Docker Compose service as daemon if not running
      command: docker-compose -f /home/vagrant/docker-compose.yml up -d
      when: compose_status.stdout | length == 0
