network:
  name: ctf_network
  subnet: 10.128.0.0/9

# Default service configuration for all exercises
service_defaults:
  init: true
  tty: true
  restart: unless-stopped
  healthcheck:
    interval: 30s
    timeout: 10s
    retries: 3
  cap_drop: ['ALL']
  cap_add: ['CHOWN', 'SETGID', 'SETUID', 'SYS_CHROOT', 'NET_ADMIN', 'NET_RAW', 'AUDIT_WRITE', 'SYS_PTRACE', 'LINUX_IMMUTABLE', 'DAC_OVERRIDE', 'FOWNER']

exercises:
  base_path: /root
  
  configs:

    cve-2018-12613:
      name: cve-2018-12613
      description: "phpMyAdmin vulnerability"
      composite_services: true
      deploy_flags: False
      template_files:
        - "Dockerfile"      
      template_vars:
        WEB_PORT: "{{random_port:8000,9000}}"
        IP_ADDRESS: "{{random_ip:10.128.0.0/10}}"
      services:
        web:
          build: 
            context: "${BASE_PATH}/${CATEGORY}/${SERVICE_NAME}/web"
          environment:
            - HTTP_PORT=${WEB_PORT}
          volumes:
            - "${BASE_PATH}/${CATEGORY}/${SERVICE_NAME}/config.inc.php:/var/www/html/phpmyadmin/config.inc.php"
          depends_on:
            - cve-2018-12613_mysql
          networks:
            ctf_network:
              ipv4_address: ${IP_ADDRESS}
        mysql:
          build: 
            context: "${BASE_PATH}/${CATEGORY}/${SERVICE_NAME}/mysql"
      
vms:
  student_prefix: "student"
  groups:
    lab01:
      range: [2, 2]
      vm_suffix: "vm1"
      exercises: [cve-2018-12613]
      host_flag: False