networks:
  ctf_network:
    name: ctf_network
    internal: false
    ipam:
      config:
        - subnet: 10.156.0.0/24
services:
  cve-2018-12613_web:
    build:
      context: cve-2018-12613/web
    environment:
    - HTTP_PORT=8202
    - FLAG=flag{CTF_b37ad4dcfc310b951326df2d930f0d5c}
    depends_on:
    - cve-2018-12613_mysql
    networks:
      ctf_network:
        ipv4_address: 10.156.0.10
    init: true
    tty: true
    restart: unless-stopped
    healthcheck: &id001
      interval: 30s
      timeout: 10s
      retries: 3
    cap_drop: &id002
    - ALL
    cap_add: &id003
    - CHOWN
    - SETGID
    - SETUID
    - SYS_CHROOT
    - NET_ADMIN
    - NET_RAW
    - AUDIT_WRITE
    - SYS_PTRACE
    - LINUX_IMMUTABLE
    - DAC_OVERRIDE
    - FOWNER
    container_name: cve-2018-12613_web
  cve-2018-12613_mysql:
    build:
      context: cve-2018-12613/mysql
    environment:
    - WEBSERVER=10.156.0.10
    networks:
      ctf_network:
        ipv4_address: 10.156.0.20
    init: true
    tty: true
    restart: unless-stopped
    healthcheck: *id001
    cap_drop: *id002
    cap_add: *id003
    container_name: cve-2018-12613_mysql