networks:
  arpspoofing:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24

services:
  arpspoofing_generator:
    build:
      context: ./arpspoofing/generator
    environment:
      - DESTINATION=172.30.0.11
      - FLAG=flag{arp_spoof_mitm_success}
    networks:
      arpspoofing:
        ipv4_address: 172.30.0.12
    mac_address: "00:00:00:00:00:01"
    init: true
    tty: true
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - CHOWN
      - SETGID
      - SETUID
      - SYS_CHROOT
      - AUDIT_WRITE
      - SYS_PTRACE
      - LINUX_IMMUTABLE
      - DAC_OVERRIDE
      - FOWNER
    container_name: arpspoofing_generator

  arpspoofing_blackhole:
    build:
      context: ./arpspoofing/blackhole
    networks:
      arpspoofing:
        ipv4_address: 172.30.0.11
    mac_address: "00:00:00:00:00:02"
    init: true
    tty: true
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - CHOWN
      - SETGID
      - SETUID
      - SYS_CHROOT
      - AUDIT_WRITE
      - SYS_PTRACE
      - LINUX_IMMUTABLE
      - DAC_OVERRIDE
      - FOWNER
    container_name: arpspoofing_blackhole

  arpspoofing_jumpbox:
    build:
      context: ./arpspoofing/jumpbox
    ports:
      - "2240:22"
    networks:
      arpspoofing:
        ipv4_address: 172.30.0.10
    mac_address: "00:00:00:00:00:03"
    init: true
    tty: true
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_RAW
      - NET_ADMIN
    container_name: arpspoofing_jumpbox
