# -*- mode: ruby -*-
# vi: set ft=ruby :

hosts = {
  "server01" => "10.0.0.10",
  "server02" => "10.8.0.10",
  "server03" => "10.16.0.10",
  "server04" => "10.24.0.10",
  "server05" => "10.32.0.10",
  "server06" => "10.40.0.10",
  "server07" => "10.48.0.10",
  "server08" => "10.56.0.10",
  "server09" => "10.64.0.10",
  "server10" => "10.72.0.10",
  "server11" => "10.80.0.10",
  "server12" => "10.88.0.10",
  "server13" => "10.96.0.10",
  "server14" => "10.104.0.10",
  "server15" => "10.112.0.10",
  "server16" => "10.120.0.10",
  "server17" => "10.128.0.10",
  "server18" => "10.136.0.10",
  "server19" => "10.144.0.10",
  "server20" => "10.152.0.10",
  "server21" => "10.160.0.10",
  "server22" => "10.168.0.10",
  "server23" => "10.176.0.10",
  "server24" => "10.184.0.10",
  "server25" => "10.192.0.10",
  "server26" => "10.200.0.10",
  "server27" => "10.208.0.10",
  "server28" => "10.216.0.10",
  "server29" => "10.224.0.10",
  "server30" => "10.232.0.10",
  "server31" => "10.240.0.10",
  "server32" => "10.248.0.10"
}

Vagrant.configure("2") do |config|
  hosts.each do |name, ip|
    config.vm.define name do |machine|
      machine.vm.box = "generic/ubuntu2204"
      machine.vm.hostname = "%s" % name
      machine.vm.network "private_network", ip: ip
      machine.vm.provider "libvirt" do |vm|
        vm.memory = "2048"
        vm.mgmt_attach = false
      end
      machine.vm.provision "ansible" do |ansible|
        ansible.playbook = "basicvm.yml"
      end      
    end
  end
end
