# -*- mode: ruby -*-
# vi: set ft=ruby :

hosts = {
  # "server31" => "10.10.31.10",
  # "server32" => "10.10.32.10",
  # "server33" => "10.10.33.10",
  # "server34" => "10.10.34.10",
  # "server35" => "10.10.35.10",
  # "server36" => "10.10.36.10",
  # "server37" => "10.10.37.10",
  # "server38" => "10.10.38.10",
  # "server39" => "10.10.39.10",
  # "server41" => "10.10.41.10",
  # "server42" => "10.10.42.10",
  # "server43" => "10.10.43.10",
  # "server44" => "10.10.44.10",
  # "server45" => "10.10.45.10",
  # "server46" => "10.10.46.10",
  # "server47" => "10.10.47.10",
  "server48" => "10.10.48.10",
  #"server49" => "10.10.49.10",
}

Vagrant.configure("2") do |config|
  hosts.each do |name, ip|
    config.vm.define name do |machine|
      machine.vm.box = "generic/ubuntu2204"
      machine.vm.hostname = "%s" % name
      machine.vm.network "private_network", ip: ip
      machine.vm.provider "libvirt" do |vm|
        vm.memory = "2048"
        vm.mgmt_attach = false
      end
      machine.vm.provision "ansible" do |ansible|
        ansible.playbook = "basicvm.yml"
      end      
    end
  end
end
